[tool]
[tool.poetry]
name = "FastUserBot_Deployer"
version = "1.2"
description = "Auto DEPLOY ShreedUserBot"
authors = ["🇦🇿 Owner <@DeveloperSH>"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
